version: '3.9'

services:
  mynodeapp:
  api:
    build: .
    ports:
      - 4000:5005
    environment:
      NODE_ENV: development
      PORT: 5005
      MONGO_URI: mongodb+srv://jayson:twmjtgma012@jaysoncluster.lvii2xg.mongodb.net/commerce?retryWrites=true&w=majority
      JWT_SECRET: abc123